name: news_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Satoshi
      fonts:
         - asset: assets/fonts/satoshi/Satoshi-Regular.otf
         - asset: assets/fonts/satoshi/Satoshi-Medium.otf
           weight: 500
         - asset: assets/fonts/satoshi/Satoshi-Bold.otf
           weight: 700

